config/app.default.php, config/bootstrap.php, config/routes.php, src/Controller/Component/ModulesComponent.php, src/Plugin.php, tests/TestCase/Controller/Component/ModulesComponentTest.php, tests/TestCase/PluginTest.php
This provides cakephp plugin handle.
Example use (for a module plugin):
- create a plugin `dogs` in `plugins`
- load plugin in bedita4web `config/app.php`:
```
'Plugins' => [
'Dogs' => ['autoload' => true, 'bootstrap' => true, 'routes' => true],
],
```
In `plugins/Dogs/config/bootstrap.php`:
```
use Cake\Core\Configure;
Configure::write('Modules.plugins', (array)Configure::read('Modules.plugins') + [['name' => 'dogs']]);
```
In `plugins/Dogs/config/routes.php`:
```
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
Router::plugin(
'Dogs',
['path' => '/'],
function (RouteBuilder $routes) {
$routes->connect(
'/dogs',
['controller' => 'Dogs', 'action' => 'index']
);
$routes->connect(
'/dogs/view/:id',
['controller' => 'Dogs', 'action' => 'view'],
['pass' => ['id']]
);
$routes->connect( …
```
=> feat: provide plugin handling

src/Controller/Component/SchemaComponent.php, src/Controller/ModulesController.php
This PR takes advantage of `schema` revision introduced in bedita/bedita#1406
Upon object view a specific schema revision is searched: 
* if right revision is cached => schema is valid
* on revision mismatch cache is removed if present
=> Use schema revision

config/app.default.php, src/Template/Element/Form/core_properties.twig, src/Template/Element/Form/other_properties.twig, src/View/Helper/ArrayHelper.php, src/View/Helper/SchemaHelper.php, tests/TestCase/View/Helper/ArrayHelperTest.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This provides ordered fields for `core_properties` form, by module (specifying properly in config).
For instance, in `app.php`:
```
'Modules' => [
// [...]
'users' => [
'core_attributes' => [
'username',
'password',
'confirm-password',
'name',
'surname',
'email',
],
],
]
=> #34 feat: users form fields order

config/app.default.php, src/Template/Element/Form/core_properties.twig, src/Template/Element/Form/other_properties.twig, src/Template/Pages/Modules/index.twig, src/Template/Pages/Modules/view.twig, src/View/Helper/ArrayHelper.php, src/View/Helper/SchemaHelper.php, tests/TestCase/View/Helper/ArrayHelperTest.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This PR introduces custom index properties display.
Property display configuration will be like this:
```php
'Properties' => [
'{module-name}' => [
// properties displayed in `sore` group	        
'core' => [
'key1',
'key2'.
],	             ],
// properties displayed in `index`	        
'index' => [
'key2',
'key3'.
],	             
],
],	         ],
```
Here `core` and `index` custom property sets may be defined.
* `SchemaHelper` was refactored with a new `controlOptions` method
* `core_properties.twig` and `other_properties.twig` are being simplified
=> Custom `index` properties + `core`/`other` refactor

src/Controller/Component/ModulesComponent.php, src/Controller/DashboardController.php, tests/TestCase/Controller/Component/ModulesComponentTest.php
This PR does two things:
1. upon `Dashboard` access `GET /home` on API is forced: this removes unwanted cache data upon login and enables permission changes without logout/login actions
1. if user is not logged no `module` data are available
=> Force `/home` reload + no data if unlogged

src/Shell/CacheShell.php
Cache shell has been extended: calling `bin/cake cache clear_all` also twig cache is cleared.
=> Remove twig cache in `cache clear_all`

src/Controller/LoginController.php, src/Template/Pages/Login/login.twig
This PR will allow proper `redirect` on login.
E.g. when user session is terminated user is redirected to an url like `/login?redirect=/documents`.
After a successful login user is now properly redirected to `/documents` as expected.
=> Redirect on login

src/View/Helper/SchemaHelper.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This PR adds `enum` JSON Schema type to `SchemaHelper`.
A refactor of `SchemaHelper` will be soon necessary, only minimal changes for now.
=> Enum schema type

config/app.default.php, src/View/AppView.php, tests/TestCase/View/AppViewTest.php
Using a configuration like this:
```php
'Elements' => [
'documents' => [
'Form/included' => 'MyPlugin',
],
],
```
We are able to override an element: if we're in `documents` module we can use `MyPlugin.Form/included` instead of `Form/included`
Is there a better way to do this with Cake?
=> Element override from a plugin via configuration

src/View/Helper/LinkHelper.php
Simply set an empty array as default value if `Plugins` conf is missing.
=> fix: avoid warning if Plugins conf missing

src/Controller/Component/PropertiesComponent.php, src/Template/Element/Form/other_properties.twig, tests/TestCase/Controller/Component/PropertiesComponentTest.php
Thi PR adds custom groups feature in objects view.
In configuration you may define custom groups other than `core`, `publish`, `advanced` and `other` simply like this:
```php
'Properties' => [
'players' => [
'view' => [
'core' => [
'name',
'surname',
],
'team_data' => [
'shirt_number',
'team',
'seasons',
],
],
'index' => [
'title',
'project_status',
],
],
],
```
=> Properties custom groups

src/Controller/ModulesController.php, src/Template/Element/Form/relation.twig, src/Template/Element/Form/relations.scss, webroot/css/style.css
In this PR: video thumbnail urls and images are displayed in related objects view if avilable.
TODO: use proper thumbnail for images
=> Display image and video thumbs in related object cards

config/app.default.php, src/Template/Element/Menu/menu.twig, src/Template/Pages/Dashboard/index.twig, src/View/Helper/LayoutHelper.php, tests/TestCase/View/Helper/LayoutHelperTest.php
Custom modules may be defined in plugins via configuration key `'PluginModules'`.
Usually this configuration is written by plugin bootstrap.
```php
'PluginModules' => [
// unique name
'My Module' => [
'title' => 'My Module',
// main module url
'route' => Router::url(['_name': 'my_module:index']),
// css class
'class' => [
'dashboard' => 'has-background-black icon-sample',
'menu' => 'has-background-black',
],
],
],
```
These modules are then displayed in dashboard and top-level menu.
=> Plugin modules

src/Template/Element/Form/advanced_properties.twig, src/Template/Element/Form/core_properties.twig, src/Template/Element/Form/other_properties.twig, src/Template/Element/Form/publish_properties.twig, src/Template/Pages/Modules/view.twig, src/View/Twig/BeditaTwigExtension.php
This PR fixes a bug with `json` input fields.
When a `json` property is used in elements other than `advanced` JSON formatting via `_jsonKeys` is not working as expected.
* a `_jsonKeys` configuration is used to easily share and update keys
* a new `write_config` Twig function has been introduced
TODO: there's a formatting issue, probably caused by moving `{{ Form.control('_jsonKeys',...) }}` stil to be fixed.
=> Fix `json` formatting in all elements

composer.json
https://github.com/bedita/php-sdk/pull/18 has introduced a dependence to `monolog/monolog` dev.
This PR add a stability flag `@dev` on `monolog` to avoid conflicts on `composer install/update`
=> fix: add stability flag for monolog dependencies

src/Template/Pages/Dashboard/index.twig
This hides `Import` module link, when no import filters are available.
This fixes #154
=> feat: hide import if no import filters available

src/Controller/ImportController.php, tests/TestCase/Controller/ImportControllerTest.php
* flash error messages are used for every error type - more consistent, no page change
* more precise upload error messages from error codes http://php.net/manual/en/features.file-upload.errors.php
=> Improve file import error messages

config/bootstrap.php, src/Controller/AppController.php, src/Controller/LoginController.php, src/Template/Pages/Login/login.twig, src/View/AppView.php, tests/TestCase/Controller/LoginControllerTest.php
User timezone is saved in session upon login. This is needed to complete #163 
It must be calculated via Javascript since there's no way to know it from HTTP. 
This timezone is used only to display date times from PHP, internally only `UTC` is (or should be) used.
In the JS snipped at login also DST (daylight saving time) is considered.
We do not track user timezone changes during session... but we can live with that I think :wink:
=> Setup user `timezone` at login

config/app.default.php, config/bootstrap.php, src/Controller/Component/ProjectConfigurationComponent.php, src/Controller/ModulesController.php, src/View/Helper/SchemaHelper.php, tests/TestCase/Controller/Component/ProjectConfigurationComponentTest.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This PR fixes #169 
* a new `ProjectConfigurationComponent` has been introduced to handle project configuration from API via `/config`
* configuration is saved in a ner `_project_config_` cache, multiple projects are supported; configuration store in `Project` app configuration key; this way `I18n` configuration from API will be available via `Configure::read('Project.I18n')`
* `SchemaHelper` was changed in order to use a `select` if a list of languages is defined `'Project.I18n.languages'` config otherwise a normal text input is used
`SchemaHelper` needs an urgent refactor (in a new issue)
=> Project `lang` select #169

src/Controller/TrashController.php, src/Template/Pages/Trash/index.twig, tests/TestCase/Controller/TrashControllerTest.php
When an error occurs on `restore` or `delete` actions from `Trash` index redirect should point to index itself.
Currently on a bulk action if an error occurs redirect will point to single object trash view. This behavior makes sense restoring or removing an object from single item trash view, not from trash index.
=> Redirect to list view on actions from list

src/Controller/Component/PropertiesComponent.php, tests/TestCase/Controller/Component/PropertiesComponentTest.php
This PR fixes a bug in `other` properties groups, as items listed in `other` default or custom configuration were not displayed.
A test case has been added with this case.
=> Fix `other` properties display

src/Template/Layout/default.twig
This fixes a js plugin registration issue.
Solution: `default.twig` template include first `pluginsJsBundle` then other js bundles.
=> fix: script include order (plugins first)
