bedita/web

composer.json, config/routes.php, src/Controller/ModulesController.php, src/Model/API/BEditaClient.php, src/Template/Element/commands_menu.twig, src/View/Helper/LinkHelper.php
This provides `DELETE` single object, from `delete` button in object view.
Extras: php-cs config for composer.
=> feat: delete single object

composer.json, config/routes.php, src/Controller/AppController.php, src/Controller/ModulesController.php, src/Controller/TrashController.php, src/Model/API/BEditaClient.php, src/Template/Element/commands_menu.twig, src/Template/Element/commands_menu_trash.twig, src/Template/Element/list_objects_trash.twig, src/Template/Trash/index.twig, src/Template/Trash/view.twig
This provides basic trash module.
Each module can access his own trashcan at `/trash?filter[type]=<object_type>`.
Trashcan provides single objects `restore` and `delete`.
=> feat: trash module, trashcan handling

src/Controller/DashboardController.php, src/Controller/ModulesController.php, src/Controller/TrashController.php, src/Template/Dashboard/display.twig, src/Template/Element/Flash/error.ctp, src/Template/Element/Flash/error.twig, src/Template/Element/Flash/info.twig, src/Template/Element/Flash/success.ctp, src/Template/Element/Flash/success.twig, src/Template/Element/Flash/warning.twig, src/Template/Element/message.twig, src/Template/Element/messages.twig, src/Template/Layout/default.twig, src/Template/Modules/index.twig, src/Template/Modules/view.twig, src/Template/Trash/index.twig, src/Template/Trash/view.twig, src/View/AppView.php
This provides basic flash messages on controllers.
Usage:
```
$this->Flash->info('This is an info');
$this->Flash->warning('This is a warning');
$this->Flash->error('This is an error');
$this->Flash->success('This is a success');
```
=> feat: flash messages

config/.env.default, config/app.default.php, config/bootstrap.php, src/Controller/Component/SchemaComponent.php, src/Controller/ModulesController.php, src/Model/API/BEditaClient.php, src/Template/Element/Property/date.twig, src/Template/Element/Property/string.twig, src/Template/Element/Property/text.twig, src/Template/Element/form_other_properties.twig, src/View/AppView.php, src/View/Helper/PropertyHelper.php
* configuration moved to `dotenv` as default,
* new `SchemaComponent` to store and handle schema data via simple cache (to be improved)
* `PropertyHelper` to display dynamic properties
Dynamic property tags are in currently in `Element/Property/{name}.twig` but there are many other (better) solutions
=> JSON Schema usage

src/Controller/ModulesController.php, src/Model/API/BEditaClient.php, src/Template/Error/error400.twig, src/Template/Error/error500.twig, src/Template/Layout/default.twig, src/Template/Layout/error.twig, src/View/AppView.php, src/View/Event/TwigListener.php, src/View/Twig/BeditaTwigExtension.php
This provides simple error handling throw `Flash` messages, plus  custom template for errors 400 and 500.
=> feat: error handling

src/Application.php, src/Controller/AppController.php, src/Controller/Component/ModulesComponent.php, src/Controller/Component/SchemaComponent.php, src/Controller/DashboardController.php, src/Controller/ErrorController.php, src/Controller/LoginController.php, src/Controller/ModulesController.php, src/Controller/TrashController.php, src/Model/API/BEditaClient.php, src/Model/API/BEditaClientException.php, src/View/AjaxView.php, src/View/AppView.php, src/View/Helper/SchemaHelper.php, src/View/Twig/BeditaTwigExtension.php, tests/TestCase/ApplicationTest.php, tests/TestCase/Controller/Component/ModulesComponentTest.php, tests/TestCase/Controller/Component/SchemaComponentTest.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This is mainly a proposal: adding scalar type hints to method parameters, and return type hints where possible.
=> Add many return & static type hints

src/View/Helper/ThumbHelper.php, tests/TestCase/View/Helper/ThumbHelperTest.php
This provides #55 
Thumb helper handles `acceptable` and `ready`.
Bonus: verify `url` is available too.
=> #55 feat: thumb handle acceptable and ready

src/Controller/ImportController.php, src/Controller/ModulesController.php, src/Controller/TrashController.php
After bedita/php-sdk#13 we can display all error details coming from API client
=> feat: display complete error details

src/Template/Element/Form/included.twig, src/View/Helper/ThumbHelper.php, tests/TestCase/View/Helper/ThumbHelperTest.php
This provides thumb status in view. Ref.: #55
=> #55 feat: view thumb status

src/Core/Result/ImportResult.php, src/Core/Result/Result.php, src/Template/Pages/Import/index.twig, tests/TestCase/Controller/ImportControllerTest.php
=> feat: import better result

src/Template/Element/Form/relations.twig, webroot/js/config/config.js
=> New Vue delimiter

src/Controller/AppController.php, src/Controller/ModulesController.php
This fixes users save on empty password (do not change password, in this case)
=> fix: save users empty password

src/Template/Element/Form/included.twig, src/Template/Element/Modules/thumb.twig, src/Template/Pages/Modules/index.twig, src/View/Helper/ThumbHelper.php, tests/TestCase/View/Helper/ThumbHelperTest.php
This provides thumbs for `images` in generic module index page
=> #70 feat: thumbnails in images index

src/View/Helper/SchemaHelper.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This PR fixes #84 
A `checked` key is added to `Form.control` array
=> Fix checkbox from schema #84 

src/Template/Element/Form/included.twig, src/Template/Element/Modules/thumb.twig
In this PR:
* display provider thumbnail (usually video) if available in items list
* embed provider video if available
* display stream fields like metadata, without input
=> Improve stream details

src/Controller/ModulesController.php, src/Template/Element/Form/advanced_properties.twig, src/Template/Element/Form/publish_properties.twig, src/Template/Pages/Modules/view.twig
This PR fixes #67 
A `properties` array will be available to view containing a `key` for each group and an array of corresponding attributes names and values.
=> Introduce properties groups in modules view #67

src/View/Helper/SchemaHelper.php, tests/TestCase/View/Helper/SchemaHelperTest.php
This provides basic handling for schema type array (#115), as multiple checkbox list.
=> feat: handle schema type array

src/Template/Layout/js/app/directives/jsoneditor.js, webroot/js/app.bundle.js
=> fix: jsoneditor vue directive for save extra

src/Template/Element/Form/custom_left.twig, src/Template/Element/Form/custom_right.twig, src/Template/Pages/Modules/view.twig, src/View/AppView.php
* two empty elements `custom_right` and `custom_left` that can be overridden via plugin
* custom element path rule changed, new element path can be defined in plugin
=> Custom element templates from plugins in fixed positions

src/Template/Pages/Modules/index.twig
=> feat: confirm message on delete item, in index

src/Core/Filter/ImportFilter.php, src/Core/Filter/ReadCSVTrait.php, src/Core/Result/ImportResult.php, src/Core/Result/Result.php, src/Template/Pages/Import/index.twig, tests/TestCase/Core/Filter/ReadCSVTraitTest.php, tests/files/import.csv
This PR adds `ReadCSVTrait` with CSV read related methods to be used by import filters.
Related test and some minor changes on `ImportFilter` and `ImportResult` are also included.
=> CSV read trait

src/Template/Pages/Import/index.twig
Simply convert `\n`  into `<br>` in import result
=> feat: format import result converting new line "\n" to "<br>"

src/Core/Result/Result.php, tests/TestCase/Core/Result/ResultTest.php
This PR adds to simple `addMessage` and `increment` methods. 
Custom counter and message names are in subclasses are possible.
=> feat: `addMessage` and `increment` methods

src/Controller/AppController.php, src/Controller/ErrorController.php, src/Controller/ExportController.php, src/Controller/ImportController.php, src/Controller/ModelController.php, src/Controller/ModulesController.php, src/Controller/TrashController.php, src/Controller/UserProfileController.php
Refactor to properly use `beforeFilter` and `beforeRender` in controllers.
TODO:
- verify controllers in plugins
- human tests
=> beforeFilter and beforeRender return ?Response

composer.json
super minor script add to composer.json
=> minor chore: code coverage script added

tests/TestCase/Controller/AppControllerTest.php
=> fix: failing test on user token

config/schema_properties.php, src/Core/Utility/Form.php, src/View/Helper/SchemaHelper.php
check if Model View shows the model of a relation or an object_type correctly 
fixes: #258
=> #258 fix: model View

config/routes.php, src/Controller/ImportController.php, tests/TestCase/Controller/ImportControllerTest.php
=> Store import result in session and redirect to index

src/Controller/ExportController.php
This provides response data meta as csv field in export
=> feat: meta fields in export

src/Controller/ExportController.php
Refactor in export csv.
Extra handled as json serialized.
Bonus: `id` field in export csv.
=> Export: serialize extra as json

config/relations.php, src/Controller/Component/SchemaComponent.php, src/Controller/ModulesController.php
After #296 `children` relations on filder was not correctly displayed...
=> Restore `children` relation on folders

.travis.yml
This way we should avoid the infamous `upload` CI error...
=> use 4.0.0-RC2 docker img
